// Curated short agent names used to auto-generate a starting name from a seed.
// Source of truth for the CLI, desktop, and vscode onboarding + add-agent flows.
//
// HARD RULES (do not violate when editing):
// 1. Every name is 2 to 5 characters, capitalized, letters only.
// 2. No duplicates.
// 3. No trademarks (Siri, Alexa, Echo, Cortana, Kenzo, etc.).
// 4. No recognizable characters from copyrighted franchises
//    (Roo, Obi, Neo, Yoda, Mario, Link, Pikachu, etc.).
// 5. Pronounceable across English-ish and Japanese-ish phonetics.
//
// The mix is roughly 60% short international names and 40% Japanese-leaning
// soft-syllable names that fit the "Tomomo" naming aesthetic.
export const AGENT_NAMES: readonly string[] = [
  // Japanese-leaning
  "Momo",
  "Lulu",
  "Yuki",
  "Taro",
  "Nori",
  "Mika",
  "Suzu",
  "Riko",
  "Aya",
  "Haru",
  "Kou",
  "Rin",
  "Emi",
  "Kiko",
  "Yumi",
  "Sachi",
  "Chiyo",
  "Hina",
  "Mai",
  "Akira",
  "Naoko",
  "Shiro",
  "Umi",
  "Kanna",
  "Ryo",
  "Saki",
  "Hiro",
  "Nao",
  "Yui",
  "Kenji",
  "Aiko",
  "Jun",
  "Noa",
  "Toma",
  "Yuna",
  "Kana",
  "Tora",
  "Sana",
  "Miku",
  "Rei",
  "Kaito",
  "Haki",
  "Nana",
  "Kira",
  "Mina",
  "Hoshi",
  "Ami",
  // Short international
  "Mark",
  "Luna",
  "Kai",
  "Finn",
  "Rio",
  "Nico",
  "Remi",
  "Toby",
  "Eli",
  "Milo",
  "Zara",
  "Iris",
  "Nia",
  "Leo",
  "Ivy",
  "Max",
  "Ada",
  "Jax",
  "Cleo",
  "Pip",
  "Lou",
  "Theo",
  "Mae",
  "Wren",
  "Bea",
  "Otto",
  "Elle",
  "Jett",
  "Skye",
  "Hugo",
  "Wyn",
  "Kit",
  "Nell",
  "Poe",
  "Sol",
  "Vale",
  "Zev",
  "Noor",
  "Tali",
  "Cass",
  "Dove",
  "Gale",
  "Haze",
  "Indy",
  "Jude",
  "Koa",
  "Lark",
  "Mira",
  "Nyx",
  "Onyx",
  "Pax",
  "Quin",
  "Roan",
  "Sage",
  "Una",
  "Vex",
  "Will",
  "Xia",
  "Yara",
  "Zion",
  "Alba",
  "Bree",
  "Clem",
  "Dara",
  "Enzo",
  "Fia",
  "Hex",
  "Ivo",
  "Joa",
  "Lyra",
  "Mox",
  "Piri",
  "Tao",
  "Vida",
  "Wes",
  "Yuri",
  "Ziv",
  "Aida",
  "Bodie",
  "Chess",
  "Dune",
  "Ember",
  "Fox",
  "Gem",
  "Hana",
  "Indra",
  "Juno",
  "Koda",
  "Lira",
  "Moss",
  "Nova",
  "Olla",
  "Pippa",
  "Rhea",
  "Sela",
  "Teja",
  "Ulla",
  "Wen",
  "Yuli",
  "Zuri",
  "Amel",
];

// FNV-1a 32-bit hash used to map a seed to a name index. Uses the same FNV
// base as seededRng in character.ts but skips the xorshift mutation step,
// so the name index and the character RNG draws are decoupled and name /
// shape do not correlate predictably.
function hashSeed(seed: string): number {
  let s = 0x811c9dc5;
  for (let i = 0; i < seed.length; i++) {
    s ^= seed.charCodeAt(i);
    s = Math.imul(s, 0x01000193);
  }
  return s < 0 ? ~s + 1 : s;
}

export function generateAgentName(seed: string): string {
  const idx = hashSeed(seed) % AGENT_NAMES.length;
  return AGENT_NAMES[idx]!;
}
